-- MySQL Script generated by MySQL Workbench
-- Qua 24 Mai 2017 09:41:57 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projeto2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto2` DEFAULT CHARACTER SET utf8 ;
USE `projeto2` ;

-- -----------------------------------------------------
-- Table `projeto2`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto2`.`turma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `situacao` TINYINT(1) NOT NULL DEFAULT 1,
  `avatar` VARCHAR(45) NULL,
  `dataInicio` DATE NULL,
  `dataTermino` DATE NULL,
  `cargaHTotal` INT(11) NULL,
  `cargaHDiaria` INT(11) NULL,
  `turno` VARCHAR(6) NULL,
  `quantidadeDeDias` INT(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTurma_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto2`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto2`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `nota1` FLOAT NULL DEFAULT 0,
  `nota2` FLOAT NULL DEFAULT 0,
  `nota3` FLOAT NULL DEFAULT 0,
  `avatar` VARCHAR(45) NULL,
  `fk_turma_aluno` INT NOT NULL,
  `media` FLOAT NULL,
  PRIMARY KEY (`id`, `fk_turma_aluno`),
  UNIQUE INDEX `idaluno_UNIQUE` (`id` ASC),
  INDEX `fk_aluno_Turma_idx` (`fk_turma_aluno` ASC),
  CONSTRAINT `fk_aluno_Turma`
    FOREIGN KEY (`fk_turma_aluno`)
    REFERENCES `projeto2`.`turma` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto2`.`registro_presenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto2`.`registro_presenca` (
  `idregistro_presenca` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `presente` TINYINT(1) NOT NULL,
  `fk_aluno_registro` INT NOT NULL,
  PRIMARY KEY (`idregistro_presenca`, `fk_aluno_registro`),
  INDEX `fk_registro_presenca_aluno1_idx` (`fk_aluno_registro` ASC),
  CONSTRAINT `fk_registro_presenca_aluno1`
    FOREIGN KEY (`fk_aluno_registro`)
    REFERENCES `projeto2`.`aluno` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `projeto2`;

DELIMITER $$
USE `projeto2`$$
CREATE DEFINER = CURRENT_USER TRIGGER `projeto2`.`turma_BEFORE_INSERT` BEFORE INSERT ON `turma` FOR EACH ROW
BEGIN
 SET NEW.quantidadeDeDias = NEW.cargaHTotal/NEW.cargaHDiaria;
END
$$

USE `projeto2`$$
CREATE DEFINER = CURRENT_USER TRIGGER `projeto2`.`turma_BEFORE_UPDATE` BEFORE UPDATE ON `turma` FOR EACH ROW
BEGIN
SET NEW.quantidadeDeDias=NEW.cargaHTotal/NEW.cargaHDiaria;
END
$$

USE `projeto2`$$
CREATE DEFINER = CURRENT_USER TRIGGER `projeto2`.`aluno_BEFORE_INSERT` BEFORE INSERT ON `aluno` FOR EACH ROW
BEGIN
SET NEW.media = (NEW.nota1 + NEW.nota2 + NEW.nota3)/3;
END
$$

USE `projeto2`$$
CREATE DEFINER = CURRENT_USER TRIGGER `projeto2`.`aluno_BEFORE_UPDATE` BEFORE UPDATE ON `aluno` FOR EACH ROW
BEGIN
SET NEW.media = (NEW.nota1 + NEW.nota2 + NEW.nota3)/3;
END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
